title: John ODonnell  # your name (or website title) here
logo: "images/Head_Shot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A home page to expand on my data science projects. All source code can be found on my GitHub profile!
  <br><br>
  <a href="https://www.linkedin.com/in/johnodonnell93">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
classes: wide
